apiVersion: v1
kind: Service
metadata:
  name: keycloak-production
  namespace: user-service
  labels:
    app: keycloak-production
spec:
  ports:
    - port: 53582
      targetPort: 8080
  selector:
    app: keycloak-production